# Set Java lang for Travis CI.
language: java
install: true

jdk: oraclejdk11

sudo: false

# Notifications
notifications:
  email:
    recipients:
      - mallet322@gmail.com
    on_success: never # default: change
    on_failure: always # default: always